editSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/textarea:

listSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:

hierarchySuccess:
  stylesheets:
    /vendor/jstree/themes/default/style.min.css:
    fullWidthTreeView:
  javascripts:
    /vendor/jstree/jstree.min:
    /js/treeView:
    /js/treeviewPager:   
    /js/treeviewTypes:
    /js/hierarchy:
    /js/pager:    
