editSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/textarea:

listSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:

homeSuccess:
  stylesheets:
    /vendor/jstree/themes/default/style.min.css:
    fullWidthTreeView:
  javascripts:
    /vendor/jstree/jstree.min.js:
    treeviewTypes:
    pager:
    treeViewPager:
    /plugins/arBcuPlugin/js/homeHierarchy:

indexSuccess:
  stylesheets:
    /vendor/jstree/themes/default/style.min.css:
    fullWidthTreeView:
  javascripts:
    /vendor/jstree/jstree.min.js:
    treeviewTypes:
    pager:
    treeViewPager:
    /plugins/arBcuPlugin/js/homeHierarchy:
    /plugins/arBcuPlugin/js/BCU_custom:

